(()=>{
  const css=`
  .intel-monitor{margin:18px 0 20px}.monitor-title{display:flex;align-items:flex-end;justify-content:space-between;gap:12px;margin-bottom:12px}.monitor-title h3{margin:0;font-size:17px}.monitor-title p{margin:4px 0 0;color:#7d8782;font-size:12px}.monitor-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.monitor-card{background:#fff;border:1px solid #e7ece9;border-radius:14px;padding:14px}.monitor-card span{display:block;color:#7d8782;font-size:11px}.monitor-card strong{display:block;margin:6px 0 2px;font-size:22px}.monitor-card small{color:#8d9692}.source-strip{display:flex;gap:8px;overflow:auto;padding:10px 0 2px}.source-pill{min-width:max-content;border:1px solid #e4eae7;background:#fbfcfb;border-radius:999px;padding:7px 10px;font-size:11px}.source-pill b{margin-right:5px}.source-pill.ok b,.source-pill.ready b{color:#07925b}.source-pill.error b{color:#d54d4d}.source-pill.not-configured b,.source-pill.discovery-only b,.source-pill.planned b{color:#b37a10}.monitor-note{margin-top:9px;color:#77827d;font-size:11px;line-height:1.55}.candidate-feed{margin-top:14px;background:#fff;border:1px solid #e7ece9;border-radius:14px;padding:14px}.candidate-feed h4{margin:0 0 10px;font-size:13px}.candidate-row{display:grid;grid-template-columns:46px 52px minmax(250px,1fr) 86px 70px;gap:9px;padding:8px 0;border-top:1px solid #f0f3f1;align-items:center;font-size:11px}.candidate-row:first-of-type{border-top:0}.candidate-row .ctitle{font-size:12px;font-weight:600;color:#202925}.candidate-row .csource{color:#7c8782;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.candidate-priority{font-weight:800}.candidate-priority.S{color:#d94444}.candidate-priority.A{color:#b77912}.candidate-priority.B{color:#4c6b61}@media(max-width:900px){.monitor-grid{grid-template-columns:repeat(2,1fr)}.candidate-row{grid-template-columns:38px 45px 1fr}.candidate-row .csource,.candidate-row .cscore{display:none}}`;
  const st=document.createElement('style');st.textContent=css;document.head.appendChild(st);
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
  async function get(url){try{const r=await fetch(`${url}?v=${Date.now()}`);return r.ok?await r.json():null}catch{return null}}
  async function render(){
    const work=document.querySelector('#page-workbench .table-wrap');if(!work)return;
    const [health,candidates]=await Promise.all([get('./data/source-health.json'),get('./data/candidates.json')]);
    const sources=health?.sources||[];const items=candidates?.items||[];const sum=candidates?.summary||{};
    const x=sources.find(v=>v.key==='x-api');const holdings=items.filter(v=>v.signal==='资金'||v.type==='持仓').length;const official=items.filter(v=>v.trustTier==='A').length;
    const wrap=document.createElement('div');wrap.className='intel-monitor';
    wrap.innerHTML=`<div class="monitor-title"><div><h3>数据源与自动候选池</h3><p>让面试官看到：不是手填8条样例，而是系统持续在跑。</p></div><small>${health?.generatedAt?`源状态 ${new Date(health.generatedAt).toLocaleString('zh-CN',{hour12:false})}`:'初始化中'}</small></div>
    <div class="monitor-grid"><div class="monitor-card"><span>近7天候选</span><strong>${sum.total??items.length??0}</strong><small>自动抓取 + 去重</small></div><div class="monitor-card"><span>A级信源候选</span><strong>${official}</strong><small>SEC / Fed / HKEX / 政府</small></div><div class="monitor-card"><span>公开持仓信号</span><strong>${holdings}</strong><small>Form 4 / 13F / 13D-G</small></div><div class="monitor-card"><span>X热点</span><strong>${x?.status==='ok'?'已连接':'预留'}</strong><small>${x?.status==='not-configured'?'需 X API Token':'仅作热点发现'}</small></div></div>
    <div class="source-strip">${sources.slice(0,14).map(v=>`<span class="source-pill ${esc(v.status)}"><b>${v.status==='ok'||v.status==='ready'?'●':'○'}</b>${esc(v.name)} · ${esc(v.trust||'')}</span>`).join('')}</div>
    <div class="monitor-note">事实层优先一级信源；权威媒体用于补充语境；X / 小红书只用于发现热点。HKEX DI / CCASS 等公开持股数据在批量化前会先核对数据许可，不绕过授权。</div>
    <div class="candidate-feed"><h4>自动候选 Top 6</h4>${items.slice(0,6).map(v=>`<div class="candidate-row"><span class="candidate-priority ${esc(v.priority)}">${esc(v.priority)}</span><span>${esc(v.signal)}</span><span class="ctitle">${esc(v.title)}</span><span class="csource">${esc(v.source)}</span><span class="cscore">${esc(v.score)}分</span></div>`).join('')||'<div class="monitor-note">小时任务首次运行后，这里会自动出现候选事件。</div>'}</div>`;
    work.parentNode.insertBefore(wrap,work);
  }
  document.addEventListener('DOMContentLoaded',()=>setTimeout(render,150));
})();
